### ISSUE TITLE
Address with ` character not recognized

### ISSUE THREAD

**Issue by rikwillems** [michielgerritsen/extract-address-parts#6]
Some French customers use the ` in their address. The extractor fails on these addresses.

**Comment by rikwillems** [comment]
See https://github.com/michielgerritsen/extract-address-parts/pull/7

**Comment by michielgerritsen** [comment]
Thanks, it's merged and release as [v1.0.5](https://github.com/michielgerritsen/extract-address-parts/releases/tag/v1.0.5)
